name: Build, test and deploy

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        java: [17, 21]
    name: Java ${{ matrix.java }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Java ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build with Maven
      run: ./mvnw install --no-transfer-progress -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      id: mvnInstall
    - name: Run tests
      run: ./mvnw test jacoco:report-aggregate -B
      id: mvnTest
    - name: Coveralls Finished
      uses: coverallsapp/github-action@v2
      with:
        flag-name: run-${{ join(matrix.*, '-') }}
        parallel: true
  finish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@v2
        with:
          parallel-finished: true
          carryforward: "run-17,run-21"
